cs50/cs50/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('firstapp/', include("firstapp.urls")), # include all urls from the firstapp app(module)
    path('newyear/', include("newyear.urls")),
    path('todo/', include("todo.urls")),
    path('flights/', include("flights.urls")),
    path('users/',include("users.urls"))
]

cs50/todo/urls.py
import imp
from django.urls import path
from . import views


app_name = "todo"  # define namespace for Django to find urls in this app

urlpatterns = [
    path('', views.index, name="index"),
    path('add/', views.add, name="add"),
]

cs50/todo/models.py
import email
from django.db import models

# Create your models here

# a toy User table example to test django models
class Users(models.Model):
    name = models.CharField(max_length=128)   # create 'name' field
    email = models.CharField(max_length=128)  # creat 'email' field

# an Items table to represent task items 
class Items(models.Model):
    name=models.CharField(max_length=128) 
    date=models.DateField(auto_now_add=True) # automatically add date only when the object is created
    status=models.SmallIntegerField(default=0) # 0 = notstarted (default valueq§), 1 = started, 2 = finished

cs50/todo/views.py
import imp
from django.shortcuts import render
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect

# Create your views here

# define an html form using django forms
class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")  # creates a character (text) input field and does client side validation
    priority = forms.IntegerField(label = "Priority", min_value=1) # creates a numeric input field and does client side validation

def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []     # create an empty list of new tasks for current session

    return render(request,"index.html", {"tasks":  request.session["tasks"]})

def add(request):

    # if the request is of type 'POST' (when user submits a new task)
    if request.method == "POST":
        form = NewTaskForm(request.POST) # populate the form with user submitted data
        if form.is_valid():
            task = form.cleaned_data["task"]  # get the variable 'task'(defined in the NewTaskForm object) from the form's user data 
            
            request.session["tasks"] += [task]  # update list of tasks for current session

            return HttpResponseRedirect(reverse("todo:index"))  # Redirect user to list of tasks- 
                                                                # reverse("todo:index") -> resolve url for name 'index' in 'todo' app
        else:
            context = {"form": form}  # 'form' is an existing form with user data filled in
            return render(request, "add.html", context)  # display the existing form if not valid
    
    else: # render a new form for GET method
        context = {"form": NewTaskForm()}  # generate new form and pass it to the add.html page
        return render(request, "add.html", context)

cs50/todo/templates/add.html
{% extends 'layout.html' %}

{% block body %}
<h1> Add New Task: </h1>
<br />
<form action="{% url 'todo:add' %}" method ='post'>

    {% csrf_token %}
    {{form}}    <!-- uses django provided "form" parameter of NewForm object -->
    <input type="submit" value="Submit Task" />
</form>
<br />
<a href="{% url 'todo:index' %}"> View Tasks </a> 
{% endblock %}

cs50/todo/templates/add_form.html
{% extends 'layout.html' %}

{% block body %}
<h1> Add New Task: </h1>
<br />
<form action="{% url 'todo:add' %}" method ='post'>

    {% csrf_token %}
    <input type="text" name ="task"  placeholder="Add a new task"/>
    <input type="submit" value="Submit Task" />

</form>
<br />
<a href="{% url 'todo:index' %}"> View Tasks </a> 
{% endblock %}

cs50/todo/templates/index.html
{% extends "layout.html" %}  <!-- inherit and extend 'layout.html' template file (in templates folder of this app)-->

{% block body %}  <!-- name of the block to be extended -->
<h1 >To-Do list:</h1>
    <ul>
        {% for task in tasks%} <!-- "tasks" is the input variable passed to this html by django -->
        <li>{{task}}</li>
        {% endfor %}
    </ul> 
    <br />
    <a href="{% url 'todo:add' %}"> Add New Task </a>
    {% comment %}
        {% url 'todo:add' %} automatically redirects to the url path named 'add' in the 'todo' app
        (defined by app_name = "todo" in urls.py file of this app
    {% endcomment %}
{% endblock %}

cs50/todo/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title> Tasks </title>
        <style>
            body{
                margin: 20px;
            }
            h1 {
                color: red;
                text-decoration: underline;
            }
            ul{
                font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
                font-size: x-large;
            }
            a{
                font-size: x-large;
            }
        </style>
    </head>
    <body>
        {% block body%}   <!-- define a block which can be implemented by other pages that extend this layout template -->
        {%endblock%}
    </body>
</html>