cs50/cs50/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('firstapp/', include("firstapp.urls")), # include all urls from the firstapp app(module)
    path('newyear/', include("newyear.urls")),
    path('todo/', include("todo.urls")),
    path('flights/', include("flights.urls")),
    path('users/',include("users.urls"))
]

cs50/users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout')
]

cs50/users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse

# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    return render(request, 'users/index.html')

def login_view(request):
    if request.method == 'POST':
        # get the username and password from posted form
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password) # authenticate the user

        # if user is authenticated successfully
        if user is not None:
            login(request,user) # login the user
            return HttpResponseRedirect(reverse('users:index'))
        else:
            return render(request, 'users/login.html', {'message': 'username or password incorrect!'})
    
    # render login page for get request
    return render(request, 'users/login.html')

def logout_view(request):
    logout(request) # logout the session
    return render(request, 'users/login.html', {'message': 'Logged Out!'})

cs50/users/templates/users/index.html
{%extends 'users/layout.html'%}
{% block body %}
<h1> Welcome, {{request.user.first_name}}! </h1>
<div style="font-size: x-large">
    <p> 
        Username: {{request.user.username}}
        <br/>
        Email: {{request.user.email}} 
    </p>
    <a href={% url 'users:logout' %} > Logout </a>
</div>
{% endblock %}

cs50/users/templates/users/layout.html
<!DOCTYPE html>
<html lang='en'>
<head>
    <title>Users</title>
</head>
<body style="font-size: large;">
    {% block body%}
    {% endblock %}
</body>
</html>

cs50/users/templates/users/login.html
{% extends 'users/layout.html' %}

{%block body %}

<form action={% url 'users:login' %} method = 'post' style="display:block; margin-top: 30px">
    {% csrf_token %}

    <p>
    <input type='text' name='username' placeholder='Username' style='font-size: 20px'/>
    <br/>
    <input type='password' name='password' placeholder='Password' style='font-size: 20px;' />
    </p>
    <p>
    <input type='submit' value = "Login" style="width: 6em; font-size: x-large; cursor: pointer" />
    </p>
</form>
{% if message %}
    <p style="color: red; font-family: helvetica, sans-serif;"> {{message}} </p>
{% endif %}

{% endblock %}