cs50/cs50/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('firstapp/', include("firstapp.urls")), # include all urls from the firstapp app(module)
    path('newyear/', include("newyear.urls")),
    path('todo/', include("todo.urls")),
    path('flights/', include("flights.urls")),
    path('users/',include("users.urls"))
]

cs50/flights/urls.py
from django.urls import path
from . import views

app_name = 'flights'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:flight_id>', views.flight, name = 'flight'),
    path('<int:flight_id>/book', views.book, name='booking')
]

cs50/flights/models.py
from django.db import models

# Create your models here.

class Airport(models.Model):
    city = models.CharField(max_length=20)
    code = models.CharField(max_length=3)

    def __str__(self) -> str:
        return f"{self.city} ({self.code})"

class Flight(models.Model):
    origin = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="departures")   # related name is the key name that we can use to get the reverse relation 
                                                                                                # (all origin cities of specific airport - all outgoing flights from the airport)
    destination = models.ForeignKey(Airport, on_delete=models.CASCADE, related_name="arrivals") # (related_name -> key to get all incoming flights to an airport) 
    duration = models.IntegerField()

    def __str__(self):
        return f"{self.id}. {self.origin} to {self.destination}"

class Passenger(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    flight = models.ManyToManyField(Flight, blank=True, related_name="passengers")

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"

cs50/flights/views.py
from urllib.parse import non_hierarchical
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render
from .models import *

# Create your views here.
def index(request):
    return render(request, 'flights/index.html', {
        'flights': Flight.objects.all()
    })

def flight(request, flight_id):
    
    flight = Flight.objects.get(pk = flight_id)  # get the flight object from input flight id
    passengers  = flight.passengers.all() # get all passengers for given flight 
                                          #(here, .passengers method is available bacause of the related_name field we added in the Passenger model) 

    non_passangers = Passenger.objects.exclude(flight=flight) # list of passengers that are not part of the 'flight' 

    return render(request, 'flights/flight.html', {
        'flight': flight,
        'passengers': passengers,
        'non_passengers': non_passangers
        })

def book(request, flight_id):
    if request.method == 'POST':
        flight = Flight.objects.get(pk = flight_id) # get the flight object
        p_id = int(request.POST["passenger"]) # get the value of "passenger" input from the posted form (which is passenger's id)
        passenger = Passenger.objects.get(pk=p_id) # get the passenger object
        passenger.flight.add(flight) # add flight to the passenger's flight list

        return HttpResponseRedirect( reverse('flights:flight', args =(flight_id,)) ) # redirect to the flight page
    

cs50/flights/templates/flights/flight.html
{% extends 'flights/layout.html' %}

{% block body %}

<h1> Flight {{flight.id}}</h1>
<ul>
    <li>Origin: {{flight.origin}} </li>
    <li>Destination: {{flight.destination}} </li>
    <li>Duration: <span style="color: red;"> {{flight.duration}} minutes </span> </li>
</ul>
<h3> Passengers </h3>
<ul>
    {% for p in passengers %}
    <li> {{p}} </li>  
    {% empty %}
    <li> No Passengers exist </li>
    {% endfor %}
</ul>
<h3> Add Passengers </h3>
<form action="{% url 'flights:booking' flight.id %}" method='post'>
    {% csrf_token %}
    <select name="passenger" id="">
        {% for p in non_passengers %}
        <option value="{{p.id}}"> {{p}} </option>    {% comment %} 
                                                    each option is the passenger's name (object p's string value) 
                                                    and its value (for submission) going to be its id 
                                                    {% endcomment %}
        {% endfor %}
        <input type='submit' style="margin-left: 1em; size: ">
    </select>
</form>
<br/>
<a href="{% url 'flights:index' %}"> Go back to all flights </a>

{% endblock %}

cs50/flights/templates/flights/index.html
{%extends "flights/layout.html"%}

{%block body%}
    <h1> Flights </h1>
    <ul>
        {% for flight in flights%}
            <li> <a href = "{% url 'flights:flight' flight.id %}"> Flight {{flight.id}} </a> - from {{flight.origin}} to {{flight.destination}}</li> 
            {% comment %} redirect to corresponding 'flight' page using 'flight id' parameter {% endcomment %}
        {% endfor %}
    </ul>
{% endblock %}

cs50/flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title> Flights </title>
    </head>
    <body style="font-size: x-large;">
        {% block body %}
        {%endblock%}
    </body>
</html>